### ISSUE TITLE
Why are prices shuffled? Does the bot even work?

### ISSUE THREAD

**Issue by NubeBuster** [gdemos01/crypto-trading-ai-bot-basic#8]
Why are the data arrays shuffled on this line?
https://github.com/gdemos01/crypto-trading-ai-bot-basic/blob/d96250f8ddd5c7e4d0b7f46ebcffe2d62b95a0e1/Dataset.py#L185

This results in the buy and sell prices being random when running the bot. This means the results are completely random.

You will see what I am talking about when you change the following lines:
https://github.com/gdemos01/crypto-trading-ai-bot-basic/blob/d96250f8ddd5c7e4d0b7f46ebcffe2d62b95a0e1/AutoTrader.py#L17
to 
>                 print(">> BUYING $",self.trade_amount," WORTH OF BITCOIN FOR", self.account.btc_price)

and https://github.com/gdemos01/crypto-trading-ai-bot-basic/blob/d96250f8ddd5c7e4d0b7f46ebcffe2d62b95a0e1/AutoTrader.py#L30
to
>                 print(">> SELLING $",self.trade_amount," WORTH OF BITCOIN FOR", self.account.btc_price)

**Comment by qkum** [comment]
1) I can see the code is from the Class named something like "Class create_test_train_datasets():"

2) With the help of google I found the answer:
In short, it seems it is normally found code when working with machine learning/ai/neural networks/test/train data.

https://stackoverflow.com/questions/35076223/how-to-randomly-shuffle-data-and-target-in-python/43406690

I don't understand its use deeply so won't try to describe how it works.

But it has nothing to do with buying/selling - but the training of the algo.

**Comment by NubeBuster** [comment]
#10 fixes this issue

**Comment by Nubebuster** [comment]
If you see the output for running the program on the data of may 2021 you will see that the program shuffles the data for running the test as well, not only for the training.
<details>
  <summary>Output for month 5 of 2021</summary>
C:\Users\Mark\AppData\Local\Programs\Python\Python39\python.exe "C:/Users/Mark/Documents/SkyWars 2020/2021/workspace/crypto-trading-ai-bot-basic/Controller.py" --train_and_trade
2021-10-10 22:20:05.473394: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-10-10 22:20:05.474059: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.



                   ,.=ctE55ttt553tzs.,                           
               ,,c5;z==!!::::  .::7:==it3>.,                      
            ,xC;z!::::::    ::::::::::::!=c33x,                   
          ,czz!:::::  ::;;..===:..:::   ::::!ct3.                 
        ,C;/.:: :  ;=c!:::::::::::::::..      !tt3.               
       /z/.:   :;z!:::::J  :E3.  E:::::::..     !ct3.             
     ,E;F   ::;t::::::::J  :E3.  E::.     ::.     \ztL            
    ;E7.    :c::::F******   **.  *==c;..    ::     Jttk           
   .EJ.    ;::::::L                    \:.   ::.    Jttl          
   [:.    :::::::::773.    JE773zs.     I:. ::::.    It3L         
  ;:[     L:::::::::::L    |t::!::J     |::::::::    :Et3         
  [:L    !::::::::::::L    |t::;z2F    .Et:::.:::.  ::[13  CRYPTO 
  E:.    !::::::::::::L               =Et::::::::!  ::|13  TRADING 
  E:.    (::::::::::::L    .......       \:::::::!  ::|i3  AI      
  [:L    !::::      ::L    |3t::::!3.     ]::::::.  ::[13          
  !:(     .:::::    ::L    |t::::::3L     |:::::; ::::EE3         
   E3.    :::::::::;z5.    Jz;;;z=F.     :E:::::.::::II3[         
   Jt1.    :::::::[                    ;z5::::;.::::;3t3          
    \z1.::::::::::l......   ..   ;.=ct5::::::/.::::;Et3L          
     \z3.:::::::::::::::J  :E3.  Et::::::::;!:::::;5E3L           
      \cz\.:::::::::::::J   E3.  E:::::::z!     ;Zz37`            
        \z3.       ::;:::::::::::::::;='      ./355F              
          \z3x.         ::~======='         ,c253F                
            \ z3=.                      ..c5t32^                  
               =zz3==...          ...=t3z13P^                     
                    `*=zjzczIIII3zzztE3>*^`                        




> Welcome to Crypto-Trading AI
> Dataset Class Initialized
> Creating Training Data for  BTC-USD
> Loading data for  BTC-USD
>> Loading month:  2020_06
>> Loading month:  2020_07
>> Loading month:  2020_08
>> Loading month:  2020_09
>> Loading month:  2020_10
>> Loading month:  2020_11
>> Loading month:  2020_12
>> Loading month:  2021_01
>> Loading month:  2021_02
>> Loading month:  2021_03
>> Loading month:  2021_04
> Creating X,Y sets for  BTC-USD
> Finished Creating set - Size:  7731   7731  P:  4160  N:  3571
> Creating Testing Data for  BTC-USD
> Loading data for  BTC-USD
>> Loading month:  2021_05
> Creating X,Y sets for  BTC-USD
> Finished Creating set - Size:  707   707  P:  329  N:  378
2021-10-10 22:20:10.475246: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-10-10 22:20:10.476597: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2021-10-10 22:20:10.477886: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2021-10-10 22:20:10.479161: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2021-10-10 22:20:10.480438: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2021-10-10 22:20:10.481720: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusolver64_11.dll'; dlerror: cusolver64_11.dll not found
2021-10-10 22:20:10.482994: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2021-10-10 22:20:10.484255: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021-10-10 22:20:10.484644: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2021-10-10 22:20:10.489849: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
C:\Users\Mark\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\optimizer_v2\optimizer_v2.py:355: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  warnings.warn(
> New model initialized:  AutoTraderAI
> Training model -  AutoTraderAI
2021-10-10 22:20:10.824547: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)
Epoch 1/10
121/121 [==============================] - 3s 7ms/step - loss: 0.8172
Epoch 2/10
121/121 [==============================] - 1s 6ms/step - loss: 0.7372
Epoch 3/10
121/121 [==============================] - 1s 6ms/step - loss: 0.7118
Epoch 4/10
121/121 [==============================] - 1s 6ms/step - loss: 0.7005
Epoch 5/10
121/121 [==============================] - 1s 6ms/step - loss: 0.6947
Epoch 6/10
121/121 [==============================] - 1s 6ms/step - loss: 0.6924
Epoch 7/10
121/121 [==============================] - 1s 6ms/step - loss: 0.6876
Epoch 8/10
121/121 [==============================] - 1s 6ms/step - loss: 0.6850
Epoch 9/10
121/121 [==============================] - 1s 6ms/step - loss: 0.6847
Epoch 10/10
121/121 [==============================] - 1s 6ms/step - loss: 0.6861
> Trading Automatically for  ['2021_05']
#################################################################################################
#           Account Balance: $ 1000  BTC: $ 0  USD: $ 1000 
#################################################################################################
##########################################   DAY  1    #########################################
58170.36
>> Not enough BTC left in your account to buy USD 
57879.76
>> BUYING $ 100  WORTH OF BITCOIN FOR 57879.76
57600
>> BUYING $ 100  WORTH OF BITCOIN FOR 57600
57859.28
>> Not worth buying more BTC at the moment
#################################################################################################
#           Account Balance: $ 1000.4147551899931  BTC: $ 200.41475518999312  USD: $ 800 
#################################################################################################
##########################################   DAY  2    #########################################
56971.39
>> BUYING $ 100  WORTH OF BITCOIN FOR 56971.39
57127.68
>> Not worth buying more BTC at the moment
56794.79
>> BUYING $ 100  WORTH OF BITCOIN FOR 56794.79
56921.17
>> Not worth buying more BTC at the moment
#################################################################################################
#           Account Balance: $ 997.2996717961812  BTC: $ 397.2996717961812  USD: $ 600 
#################################################################################################
##########################################   DAY  3    #########################################
58009.25
>> Not worth buying more BTC at the moment
58691.72
>> Not worth buying more BTC at the moment
57990.02
>> Not worth buying more BTC at the moment
56660.13
>> BUYING $ 100  WORTH OF BITCOIN FOR 56660.13
#################################################################################################
#           Account Balance: $ 995.4776588908653  BTC: $ 495.47765889086537  USD: $ 500 
#################################################################################################
##########################################   DAY  4    #########################################
56055.18
>> BUYING $ 100  WORTH OF BITCOIN FOR 56055.18
55716.15
>> BUYING $ 100  WORTH OF BITCOIN FOR 55716.15
54301.01
>> BUYING $ 100  WORTH OF BITCOIN FOR 54301.01
53770.52
>> BUYING $ 100  WORTH OF BITCOIN FOR 53770.52
#################################################################################################
#           Account Balance: $ 961.6640768394631  BTC: $ 861.6640768394631  USD: $ 100 
#################################################################################################
##########################################   DAY  5    #########################################
54760.01
>> Not worth buying more BTC at the moment
55236.43
>> Not worth buying more BTC at the moment
57509.74
>> Not worth buying more BTC at the moment
57348.79
>> Not worth buying more BTC at the moment
#################################################################################################
#           Account Balance: $ 1019.0052875294907  BTC: $ 919.0052875294907  USD: $ 100 
#################################################################################################
##########################################   DAY  6    #########################################
57014.36
>> Not worth buying more BTC at the moment
57987.77
>> Not worth buying more BTC at the moment
56889.08
>> Not worth buying more BTC at the moment
56399.99
>> Not worth buying more BTC at the moment
#################################################################################################
#           Account Balance: $ 1003.8009176237267  BTC: $ 903.8009176237267  USD: $ 100 
#################################################################################################
##########################################   DAY  7    #########################################
56061.26
>> Not worth buying more BTC at the moment
56459.46
>> Not worth buying more BTC at the moment
57856.53
>> Not worth buying more BTC at the moment
57088.28
>> Not worth buying more BTC at the moment
#################################################################################################
#           Account Balance: $ 1014.8306559905461  BTC: $ 914.8306559905461  USD: $ 100 
#################################################################################################
##########################################   DAY  8    #########################################
57864.44
>> Not worth buying more BTC at the moment
58481.11
>> SELLING $ 100  WORTH OF BITCOIN FOR 58481.11
59078.83
>> BUYING $ 100  WORTH OF BITCOIN FOR 59078.83
58916.25
>> BUYING $ 100  WORTH OF BITCOIN FOR 58916.25
#################################################################################################
#           Account Balance: $ 1043.10432510482  BTC: $ 1043.10432510482  USD: $ 0 
#################################################################################################
##########################################   DAY  9    #########################################
58531.26
>> Not enough USD left in your account to buy BTC 
57323.38
>> Not enough USD left in your account to buy BTC 
57532.25
>> Not enough USD left in your account to buy BTC 
58177.59
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 1030.0264486143453  BTC: $ 1030.0264486143453  USD: $ 0 
#################################################################################################
##########################################   DAY  10    #########################################
59244.56
>> Not enough USD left in your account to buy BTC 
58188.3
>> Not enough USD left in your account to buy BTC 
57137.27
>> SELLING $ 100  WORTH OF BITCOIN FOR 57137.27
55536.97
>> BUYING $ 100  WORTH OF BITCOIN FOR 55536.97
#################################################################################################
#           Account Balance: $ 986.0754235945336  BTC: $ 986.0754235945336  USD: $ 0 
#################################################################################################
##########################################   DAY  11    #########################################
55097.43
>> Not enough USD left in your account to buy BTC 
55209.32
>> Not enough USD left in your account to buy BTC 
56512.79
>> Not enough USD left in your account to buy BTC 
57077.01
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 1013.4192919285916  BTC: $ 1013.4192919285916  USD: $ 0 
#################################################################################################
##########################################   DAY  12    #########################################
57225.09
>> Not enough USD left in your account to buy BTC 
56524.81
>> Not enough USD left in your account to buy BTC 
54639.93
>> Not enough USD left in your account to buy BTC 
47610.44
>> SELLING $ 100  WORTH OF BITCOIN FOR 47610.44
#################################################################################################
#           Account Balance: $ 845.3375254451607  BTC: $ 745.3375254451607  USD: $ 100 
#################################################################################################
##########################################   DAY  13    #########################################
51164
>> SELLING $ 100  WORTH OF BITCOIN FOR 51164
50101.3
>> BUYING $ 100  WORTH OF BITCOIN FOR 50101.3
48840.94
>> BUYING $ 100  WORTH OF BITCOIN FOR 48840.94
50035.26
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 887.8175173929603  BTC: $ 887.8175173929603  USD: $ 0 
#################################################################################################
##########################################   DAY  14    #########################################
49318.23
>> Not enough USD left in your account to buy BTC 
50541.71
>> Not enough USD left in your account to buy BTC 
50700.01
>> Not enough USD left in your account to buy BTC 
50148.52
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 889.827184416174  BTC: $ 889.827184416174  USD: $ 0 
#################################################################################################
##########################################   DAY  15    #########################################
49267.25
>> Not enough USD left in your account to buy BTC 
48773.22
>> Not enough USD left in your account to buy BTC 
47972.75
>> Not enough USD left in your account to buy BTC 
47664.6
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 845.7529118371424  BTC: $ 845.7529118371424  USD: $ 0 
#################################################################################################
##########################################   DAY  16    #########################################
49251.63
>> Not enough USD left in your account to buy BTC 
48941.6
>> Not enough USD left in your account to buy BTC 
46863.27
>> Not enough USD left in your account to buy BTC 
45949.95
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 815.3284410499846  BTC: $ 815.3284410499846  USD: $ 0 
#################################################################################################
##########################################   DAY  17    #########################################
45305.18
>> Not enough USD left in your account to buy BTC 
45524.19
>> Not enough USD left in your account to buy BTC 
43066.36
>> Not enough USD left in your account to buy BTC 
44323.99
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 786.4776712012768  BTC: $ 786.4776712012768  USD: $ 0 
#################################################################################################
##########################################   DAY  18    #########################################
45793.23
>> Not enough USD left in your account to buy BTC 
45136.87
>> Not enough USD left in your account to buy BTC 
42839.8
>> Not enough USD left in your account to buy BTC 
43367.99
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 769.5145626528717  BTC: $ 769.5145626528717  USD: $ 0 
#################################################################################################
##########################################   DAY  19    #########################################
39825.01
>> Not enough USD left in your account to buy BTC 
38466.44
>> Not enough USD left in your account to buy BTC 
38220.54
>> SELLING $ 100  WORTH OF BITCOIN FOR 38220.54
38184.83
>> BUYING $ 100  WORTH OF BITCOIN FOR 38184.83
#################################################################################################
#           Account Balance: $ 677.6388458648416  BTC: $ 677.6388458648416  USD: $ 0 
#################################################################################################
##########################################   DAY  20    #########################################
39389.16
>> Not enough USD left in your account to buy BTC 
40673.86
>> Not enough USD left in your account to buy BTC 
39516.53
>> Not enough USD left in your account to buy BTC 
41010.96
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 727.7921520721497  BTC: $ 727.7921520721497  USD: $ 0 
#################################################################################################
##########################################   DAY  21    #########################################
39425.92
>> Not enough USD left in your account to buy BTC 
41200.95
>> Not enough USD left in your account to buy BTC 
36928.33
>> Not enough USD left in your account to buy BTC 
36983.46
>> SELLING $ 100  WORTH OF BITCOIN FOR 36983.46
#################################################################################################
#           Account Balance: $ 656.3189923979899  BTC: $ 556.3189923979899  USD: $ 100 
#################################################################################################
##########################################   DAY  22    #########################################
36047.16
>> BUYING $ 100  WORTH OF BITCOIN FOR 36047.16
37777.77
>> Not enough USD left in your account to buy BTC 
37897.33
>> Not enough USD left in your account to buy BTC 
37108.55
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 661.1450911385837  BTC: $ 661.1450911385837  USD: $ 0 
#################################################################################################
##########################################   DAY  23    #########################################
36746.05
>> Not enough USD left in your account to buy BTC 
35535.61
>> Not enough USD left in your account to buy BTC 
32129.59
>> Not enough USD left in your account to buy BTC 
35455.39
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 631.6915388206768  BTC: $ 631.6915388206768  USD: $ 0 
#################################################################################################
##########################################   DAY  24    #########################################
35445.29
>> Not enough USD left in your account to buy BTC 
37586.42
>> Not enough USD left in your account to buy BTC 
37586.75
>> Not enough USD left in your account to buy BTC 
38950.88
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 693.9689938714403  BTC: $ 693.9689938714403  USD: $ 0 
#################################################################################################
##########################################   DAY  25    #########################################
38523
>> Not enough USD left in your account to buy BTC 
37012.53
>> Not enough USD left in your account to buy BTC 
37937.9
>> Not enough USD left in your account to buy BTC 
38336.69
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 683.0262676391729  BTC: $ 683.0262676391729  USD: $ 0 
#################################################################################################
##########################################   DAY  26    #########################################
39761.64
>> Not enough USD left in your account to buy BTC 
40139.87
>> Not enough USD left in your account to buy BTC 
38599.75
>> Not enough USD left in your account to buy BTC 
38962.1
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 694.1688951858968  BTC: $ 694.1688951858968  USD: $ 0 
#################################################################################################
##########################################   DAY  27    #########################################
38033.87
>> Not enough USD left in your account to buy BTC 
39603.8
>> Not enough USD left in your account to buy BTC 
39091.2
>> Not enough USD left in your account to buy BTC 
38530.44
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 686.4782176994178  BTC: $ 686.4782176994178  USD: $ 0 
#################################################################################################
##########################################   DAY  28    #########################################
37030.01
>> Not enough USD left in your account to buy BTC 
36426.4
>> Not enough USD left in your account to buy BTC 
35668.03
>> Not enough USD left in your account to buy BTC 
35964.9
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 640.7692321120078  BTC: $ 640.7692321120078  USD: $ 0 
#################################################################################################
##########################################   DAY  29    #########################################
36937.2
>> Not enough USD left in your account to buy BTC 
35134.81
>> Not enough USD left in your account to buy BTC 
33707.58
>> Not enough USD left in your account to buy BTC 
34323.73
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 611.5292998262163  BTC: $ 611.5292998262163  USD: $ 0 
#################################################################################################
##########################################   DAY  30    #########################################
35486.97
>> Not enough USD left in your account to buy BTC 
36044.1
>> Not enough USD left in your account to buy BTC 
#################################################################################################
#           Account Balance: $ 642.1803002140537  BTC: $ 642.1803002140537  USD: $ 0 
#################################################################################################

Process finished with exit code 0

  ```javascript
  console.log("I'm a code block!");
  ```
  
</details>
